language: go
sudo: false

matrix:
  include:
    - os: linux
      go: 1.7.x
    - os: linux
      go: 1.8
    - os: linux
      go: tip

install:
  - echo "This is an override of the default install deps step in travis."

script:
  - go build