language: go
sudo: false

matrix:
  include:
    - os: linux
      go: 1.7.x
    - os: linux
      go: 1.8

install:
  - echo "This is an override of the default install deps step in travis."
before_script:
  - go get -u github.com/fatih/color
  - go get -u github.com/PuerkitoBio/goquery
  - go get -u github.com/boltdb/bolt/...
script:
  - go build